name: Keep Backend Alive

on:
  schedule:
    - cron: "*/10 * * * *"   # runs every 10 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Send Ping Request
        run: curl https://smart-internship-backend.onrender.com/ping
